- name: TWGCB01-014-0001 Disable cramfs filesystem support
  hosts: all
  become: yes
  tasks:
    - name: Ensure cramfs is blacklisted in modprobe configuration
      copy:
        dest: /etc/modprobe.d/cramfs.conf
        content: |
          install cramfs /bin/false
          blacklist cramfs
        owner: root
        group: root
        mode: '0644'

    - name: Remove cramfs module if loaded
      command: modprobe -r cramfs
      register: modprobe_result
      failed_when: modprobe_result.rc not in [0, 1]
      ignore_errors: yes

    - name: Verify cramfs module is removed
      shell: lsmod | grep -w cramfs
      register: cramfs_check
      failed_when: cramfs_check.rc == 0
      ignore_errors: yes

- name: TWGCB01-014-0002 Disable squashfs filesystem support
  hosts: all
  become: yes
  tasks:
    - name: Ensure squashfs is blacklisted in modprobe configuration
      copy:
        dest: /etc/modprobe.d/squashfs.conf
        content: |
          install squashfs /bin/false
          blacklist squashfs
        owner: root
        group: root
        mode: '0644'

    - name: Remove squashfs module if loaded
      command: modprobe -r squashfs
      register: modprobe_result
      failed_when: modprobe_result.rc not in [0, 1]
      ignore_errors: yes

    - name: Verify squashfs module is removed
      shell: lsmod | grep -w squashfs
      register: squashfs_check
      failed_when: squashfs_check.rc == 0
      ignore_errors: yes
      changed_when: squashfs_check.rc == 0



- name: TWGCB01-014-0003管理 udf 模組設定
  hosts: all
  become: true
  tasks:
    - name: Ensure /etc/modprobe.d/udf.conf contains required configuration
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/udf.conf
        block: |
          install udf /bin/false
          blacklist udf
        create: yes
        state: present

    - name: Remove udf kernel module
      ansible.builtin.command:
        cmd: modprobe -r udf
      register: udf_removal
      failed_when: udf_removal.rc not in [0, 1]
      changed_when: udf_removal.rc == 0

    - name: Ensure udf kernel module is not loaded
      ansible.builtin.shell: lsmod | grep -q '^udf'
      register: udf_loaded_check
      failed_when: false
      changed_when: false

    - name: Fail if udf module is still loaded
      ansible.builtin.fail:
        msg: "The udf module is still loaded!"
      when: udf_loaded_check.rc == 0


- name: TWGCB01-014-0004 Configure /tmp mount in /etc/fstab
  hosts: all
  become: yes
  tasks:
    - name: Ensure /tmp mount is configured in /etc/fstab
      ansible.builtin.mount:
        path: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: defaults,rw,nosuid,nodev,noexec,relatime
        dump: 0
        passno: 0
        state: mounted

# reference https://stackoverflow.com/a/48259691
- name: TWGCB01-014-0005 Add nodev option to /tmp mount and remount
  hosts: all
  become: yes
  tasks:
  - name: '/etc/fstab: Set opt "nodev" for mount point /tmp'
    lineinfile:
      path: /etc/fstab
      backup: yes
      backrefs: yes
      regexp: '^(\S+\s+/tmp\s+\S+\s+)(?!(?:\S*,)?nodev(?:,\S*)?\s+)(\S+)(\s+.+)$'
      line: '\1nodev,\2\3'
    register: fstab

  - name: 'If /tmp changed, remount'
    command: 'mount /tmp -o remount'
    when: fstab.changed

- name: TWGCB01-014-0006 Ensure /tmp has nosuid option in /etc/fstab and remount
  hosts: all
  become: yes
  tasks:
    - name: Ensure /tmp mount in /etc/fstab includes nosuid option
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^tmpfs\s+/tmp\s+tmpfs'
        line: 'tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,relatime'
        backrefs: yes
        state: present

    - name: Remount /tmp with nosuid option
      ansible.builtin.mount:
        path: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: defaults,rw,nosuid,nodev,noexec,relatime
        state: mounted

- name: TWGCB01-014-0007 Ensure /tmp has noexec option in /etc/fstab and remount
  hosts: all
  become: yes
  tasks:
    - name: Ensure /tmp mount in /etc/fstab includes noexec option
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^tmpfs\s+/tmp\s+tmpfs'
        line: 'tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,relatime'
        backrefs: yes
        state: present

    - name: Remount /tmp with noexec option
      ansible.builtin.mount:
        path: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: defaults,rw,nosuid,nodev,noexec,relatime
        state: mounted

- name: TWGCB01-014-0008, TWGCB01-014-0009, TWGCB01-014-0010 Ensure /dev/shm has nodev,nosuid,noexec option in /etc/fstab and remount
  hosts: all
  become: yes
  tasks:
    - name: Ensure /dev/shm entry exists in /etc/fstab with nodev option
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^tmpfs\s+/dev/shm\s+tmpfs'
        line: 'tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec,inode64 0 0'
        state: present

    - name: Remount /dev/shm with nodev option
      ansible.builtin.mount:
        path: /dev/shm
        src: tmpfs
        fstype: tmpfs
        opts: rw,nosuid,nodev,noexec,inode64
        state: mounted

- name: TWGCB01-014-0011~TWGCB01-014-0013
  hosts: all
  become: yes
  tasks:
    - name: Check if /var is a separate partition
      ansible.builtin.set_fact:
        is_var_separate: >-
          {{
            ansible_facts['mounts'] | selectattr('mount', 'equalto', '/var') | list | length > 0
          }}

    - name: Debug the result for /var partition check
      ansible.builtin.debug:
        msg: >
          "/var is {{ 'a separate partition' if is_var_separate else 'not a separate partition' }}."

    - name: Add warning if /var is not a separate partition
      ansible.builtin.fail:
        msg: "WARNING: /var is not a separate partition or logical volume. check https://download.nics.nat.gov.tw/UploadFile/attachfilegcb/TWGCB-01-014_Ubuntu%2022.04%20LTS政府組態基準說明文件v1.0_1130930.pdf for further imformation. Pass tasks until TWGCB01-014-0026"
      when: not is_var_separate

    - name: Force handlers to run (ensure warnings are displayed at the end)
      meta: flush_handlers

    - name: TWGCB01-014-0012-0013 Ensure /var entry exists in /etc/fstab with nodev option
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^tmpfs\s+/var\s+tmpfs'
        line: 'tmpfs /var tmpfs rw,nosuid,nodev 0 0'
        state: present
      when: not is_var_separate

    - name: Remount /var with nodev option
      ansible.builtin.mount:
        path: /var
        src: tmpfs
        fstype: tmpfs
        opts: rw,nosuid,nodev
        state: mounted
      when: not is_var_separate

    
- name: TWGCB01-014-0014~TWGCB01-014-0017
hosts: all
become: yes
tasks:
  - name: Check if /var/tmp is a separate partition
    ansible.builtin.set_fact:
      is_var_separate: >-
        {{
          ansible_facts['mounts'] | selectattr('mount', 'equalto', '/var/tmp') | list | length > 0
        }}

  - name: Debug the result for /var/tmp partition check
    ansible.builtin.debug:
      msg: >
        "/var/tmp is {{ 'a separate partition' if is_var_separate else 'not a separate partition' }}."

  - name: Add warning if /var/tmp is not a separate partition
    ansible.builtin.fail:
      msg: "WARNING: /var/tmp is not a separate partition or logical volume. check https://download.nics.nat.gov.tw/UploadFile/attachfilegcb/TWGCB-01-014_Ubuntu%2022.04%20LTS政府組態基準說明文件v1.0_1130930.pdf for further imformation. Pass tasks until TWGCB01-014-0026"
    when: not is_var_separate

  - name: Force handlers to run (ensure warnings are displayed at the end)
    meta: flush_handlers
        
    
    
- name: TWGCB01-014-0018~TWGCB01-014-0021
  hosts: all
  become: yes
  tasks:
    - name: Check if /var/log is a separate partition
      ansible.builtin.set_fact:
        is_var_separate: >-
          {{
            ansible_facts['mounts'] | selectattr('mount', 'equalto', '/var/log') | list | length > 0
          }}

    - name: Debug the result for /var/log partition check
      ansible.builtin.debug:
        msg: >
          "/var/log is {{ 'a separate partition' if is_var_separate else 'not a separate partition' }}."

    - name: Add warning if /var/log is not a separate partition
      ansible.builtin.fail:
        msg: "WARNING: /var/log is not a separate partition or logical volume. check https://download.nics.nat.gov.tw/UploadFile/attachfilegcb/TWGCB-01-014_Ubuntu%2022.04%20LTS政府組態基準說明文件v1.0_1130930.pdf for further imformation. Pass tasks until TWGCB01-014-0026"
      when: not is_var_separate

    - name: Force handlers to run (ensure warnings are displayed at the end)
      meta: flush_handlers
    
    
- name: TWGCB01-014-0022~TWGCB01-014-0025
  hosts: all
  become: yes
  tasks:
    - name: Check if /var/log/audit is a separate partition
      ansible.builtin.set_fact:
        is_var_separate: >-
          {{
            ansible_facts['mounts'] | selectattr('mount', 'equalto', '/var/log/audit') | list | length > 0
          }}

    - name: Debug the result for /var/log/audit partition check
      ansible.builtin.debug:
        msg: >
          "/var/log/audit is {{ 'a separate partition' if is_var_separate else 'not a separate partition' }}."

    - name: Add warning if /var/log/audit is not a separate partition
      ansible.builtin.fail:
        msg: "WARNING: /var/log/audit is not a separate partition or logical volume. check https://download.nics.nat.gov.tw/UploadFile/attachfilegcb/TWGCB-01-014_Ubuntu%2022.04%20LTS政府組態基準說明文件v1.0_1130930.pdf for further imformation. Pass tasks until TWGCB01-014-0026"
      when: not is_var_separate

    - name: Force handlers to run (ensure warnings are displayed at the end)
      meta: flush_handlers
    
    
- name: TWGCB01-014-0026~TWGCB01-014-0028
  hosts: all
  become: yes
  tasks:
    - name: Check if /home is a separate partition
      ansible.builtin.set_fact:
        is_var_separate: >-
          {{
            ansible_facts['mounts'] | selectattr('mount', 'equalto', '/home') | list | length > 0
          }}

    - name: Debug the result for /home partition check
      ansible.builtin.debug:
        msg: >
          "/home is {{ 'a separate partition' if is_var_separate else 'not a separate partition' }}."

    - name: Add warning if /home is not a separate partition
      ansible.builtin.fail:
        msg: "WARNING: /home is not a separate partition or logical volume. check https://download.nics.nat.gov.tw/UploadFile/attachfilegcb/TWGCB-01-014_Ubuntu%2022.04%20LTS政府組態基準說明文件v1.0_1130930.pdf for further imformation. Pass tasks until TWGCB01-014-0026"
      when: not is_var_separate

    - name: Force handlers to run (ensure warnings are displayed at the end)
      meta: flush_handlers

